rott/rt_main.c, rott/rt_util.c, rott/rt_util.h, rott/w_wad.c, rott/z_zone.c, rott/z_zone.h
It was only used in one occasion, i.e. for the `lumpinfo[]` array and we can just as well use stdlib's `realloc()` there.
=> get rid of `Z_Realloc()`

rott/rt_draw.c
=> [rt_draw.c]: Fixing wrong cast, affecting the Apogee logo animation.

rott/dukemusc.c, rott/rt_cfg.c, rott/rt_game.c, rott/rt_menu.c, rott/rt_util.c, rott/rt_util.h, rott/w_wad.c, rott/winrott.c
Entirely replace calls to the former with `M_StringJoin()`.
The latter shouldn't even be required anymore. "Guessed" file paths will be stored with their actual case, all other file names are either passed by the user (and thus expected to be correctly cased) or generated internally (and thus keep their case).
=> get rid of `GetPathFromEnvironment()` and `FixFilePath()`

rott/rt_in.c
Found this while working on my own fork. It prevented some user text input from being taken properly, and perhaps other effects.
=> rt_in.c: Fix typo in SCANCODE_TO_KEYS_ARRAY

rott/dosutil.c, rott/rt_main.c
Just a small change to fix compilation on the Haiku operating system. Tested on hrev56578.
=> Fix compilation on Haiku OS

rott/cin_main.c
It's a little hard to notice, but in the opening cinematic with the ROTT logo, you can see some missing pixels at the bottom of the logo which is not there in the DOS version. It was just a slight mistake when translating the assembly to C. This commit fixes that.
Funny enough, ROTT:LE has this bug too.
=> Fix cinematics off-by-one-pixel draw error

rott/fx_man.h, rott/fx_mixer.c, rott/rt_playr.c, rott/rt_sound.c, rott/rt_sound.h
=> update all sounds relative to the player

rott/dukemusc.c, rott/music.h, rott/rt_sound.c
Whenever `MUSIC_PlaySong()` was written, `Mix_LoadMUS_RW()` didn't exist. But now it does! So let's use it.
=> Use Mix_LoadMUS_RW() instead of saving MIDI to disk

rott/_rt_play.h, rott/rt_playr.c, rott/winrott.c
Now you look up and look down the same amount at 320x200 and 640x480.
| 320x200 | 640x480 |
|---|---|
| ![Screenshot_20240709_195217](https://github.com/fabiangreffrath/taradino/assets/6947463/7a26c7d1-9241-4a42-9b5f-904c8447961c) | ![Screenshot_20240709_195106](https://github.com/fabiangreffrath/taradino/assets/6947463/453d9073-f6f5-43eb-ad53-d21cbbb769d3) |
=> Normalize lookup/lookdown between resolutions

rott/modexlib.c, rott/rt_draw.c, rott/rt_draw.h
gcc 14 is a bit stricter with types, causing a compile errors. This PR makes the game able to build with it, without making any changes to how the game works. Let me know if you see any issue with it, I was able to play the game just fine.
=> Add fixes for gcc 14

CMakeLists.txt, rott/rt_datadir.c
Instead of saving configuration files inconsistently between shareware and registered, this PR ensures that they are saved into the same Taradino folder, in a subfolder for the name of the WAD. For registered, this is "darkwar" and for shareware this is "huntbgin". This can be expanded later for any other game WADs that could be loaded (i.e. huntbgn2.wad, or Extreme ROTT).
=> Small datadirs improvement

rott/modexlib.c
I tried this in my ROTTEN port, and it seemed to make the physics & lookup/lookdown behave a little better. It even fixed demo desync! I don't know if this the best solution, but it does get the game to run at the "intended" framerate (as far as i can see from the original source). Thoughts are appreciated.
=> Hard framerate cap of 35 fps using VBLCOUNTER

rott/rt_datadir.c, rott/rt_menu.c, rott/rt_net.c, rott/rt_ted.c, rott/rt_ted.h
Heavily work in progress. It builds under Mingw, but it doesn't do any (much needed) Windows Registry checks for things such as the Steam directory and maybe others. For both Linux and Windows, it just queries the default installation paths from the various storefronts for each platform. It works, but it's not super elegant or foolproof. This does not conflict with the XDG paths or any others.
This also needs to be modified to account for where the game could be installed with GOG under Mac OS X.
=> Pull ROTT data from various common install paths

rott/rt_in.c
The first 4 buttons are now recognized by joystick index, and the joystick ABS value is clamped to the range that ROTT expects. It's sorta playable! But you can't switch weapons or anything. Not sure how that was meant to work on a traditional gamepad. I will keep working on first-class support when I have time.
=> First steps to fixing gamepad/joystick support

rott/rt_ted.c
A logic error (I think on my part...) causes game saves to not work at all. Hard crash if you try to save a game without this fix. I haven't replaced `GetMapFileName` because its used elsewhere in the code.
=> Fix game saves not working at all

rott/modexlib.c, rott/vgatext.c
SDL2 documentation states that this is the preferred method if you want fast(er) screen updates. I don't know if there's any perceivable difference on my machine, but it's probably best practice anyways.
=> Use SDL_LockTexture() instead of SDL_UpdateTexture()

rott/_rt_acto.h, rott/rt_actor.c, rott/rt_ted.c
I went through the code at https://bitbucket.org/gamesrc-ver-recreation/rott and changed the code in various places where differences were indicated between the commercial release and source release, focusing only on gameplay changes. This fixes the E1A1 demo desync. I haven't tested the other included demos yet.
=> Apply various changes from gamesrc-ver-recreation

rott/rt_cfg.c, rott/rt_main.c, rott/rt_playr.c, rott/rt_view.c
Removes weapon scaling code added by BNA:
- Removes line in help describing how to change weapon scale
- Removes weapon scaling from keyboard input
- Removes G_weaponscale config variable
=> Remove BNA weaponscale

CMakeLists.txt, rott/rt_def.h
As of GCC 15, gnu23 is now the default C standard, which breaks taradino (as `true` and `false` are reserved keywords in C23). Taradino is already compiled using c17 under MSVC. As two of the three major C compilers now require setting the C standard in order to build the project, I would recommend setting the standard unconditionally, as I am not aware of any supported platforms this would break, hence the PR. 
If setting the standard across the board is, in fact, a problem, I can rewrite the PR to check for either GCC or msvc instead.
=> set project C standard to C17 unconditionally

rott/rt_in.c
Fixes #118
I have tested this and it seems to fix the issue. Further testing across different system configurations and some code review is necessary. It still works gracefully irregardless of mouse sensitivity, threshold, holding strafe modifier, fullscreen/windowed etc.
=> Fix mouse precision issues on Linux by using SDL's built-in mouse delta handler.
